// Data layer.
//
// The site works with zero hosting: predictions are precomputed into
// public/data.json (regenerated by build_data.py, e.g. on a schedule).
// If you deploy the Flask API and set VITE_EARNINGS_API, live data is
// preferred with a static fallback so the site is never broken.

import tickers from '../tickers.json';
import { searchStocks } from './data/searchStocks';

const API_BASE = import.meta.env.VITE_EARNINGS_API || null;

export const categoryTickers = tickers;
export const categories = Object.keys(tickers);

const nameByTicker = Object.fromEntries(searchStocks.map((s) => [s.ticker, s.name]));

let dataPromise = null;

export function loadStaticData() {
  if (!dataPromise) {
    dataPromise = fetch(`${import.meta.env.BASE_URL}data.json`, { cache: 'no-cache' })
      .then((r) => r.json())
      .then((j) => ({ stocks: j.stocks || {}, generatedAt: j.generated_at }))
      .catch((err) => {
        console.error('Failed to load data.json', err);
        return { stocks: {}, generatedAt: null };
      });
  }
  return dataPromise;
}

// Normalize either API JSON or a static-data entry into one shape.
function normalize(ticker, json) {
  if (!json) return null;
  return {
    ticker,
    name: json.company_name || ticker,
    logo: json.logo,
    website: json.website,
    sector: json.sector,
    industry: json.industry,
    description: json.description || '',
    earningsDate: json.earnings_date,
    expectedEps: json.expected_eps,
    trailingPe: json.pe_ratio,
    beta: json.beta,
    marketCap: json.market_cap,
    daysUntil: json.days_until,
    rawBeatPct: json.raw_beat_pct,
  };
}

export async function fetchStock(ticker) {
  if (API_BASE) {
    try {
      const res = await fetch(`${API_BASE}/predict?ticker=${encodeURIComponent(ticker)}`);
      if (res.ok) return normalize(ticker, await res.json());
    } catch (err) {
      console.warn(`Live API failed for ${ticker}, using static data.`, err);
    }
  }
  const { stocks } = await loadStaticData();
  const hit = normalize(ticker, stocks[ticker]);
  if (hit) return hit;
  // Not in the precomputed set: still open a detail page with name + chart.
  return {
    ticker,
    name: nameByTicker[ticker] || ticker,
    logo: null, website: null, sector: null, industry: null,
    description: '', earningsDate: null, expectedEps: null,
    trailingPe: null, beta: null, marketCap: null,
    daysUntil: null, rawBeatPct: null,
    notCovered: true,
  };
}

// Fetch a whole category at once (static lookups are instant).
export async function fetchCategory(category) {
  const list = categoryTickers[category] || [];
  const results = await Promise.all(list.map((t) => fetchStock(t).catch(() => null)));
  return results.filter(Boolean);
}
